### ISSUE TITLE
Boundary

### ISSUE THREAD

**Issue by Besjan** [Besjan/Terrain-Generator#12]
- [x] Flatten terrain outside boundary
    - [x] Use points to deform terrain #18
    - [x] Use mesh to deform terrain #17
    - [x] Check DS Implementation: LevelTerrainTool - CarveTerrain()
    - [x] Check: http://blog.almostlogical.com/2010/06/10/real-time-terrain-deformation-in-unity3d/
    - [x] Check: https://docs.unity3d.com/2020.1/Documentation/ScriptReference/Experimental.TerrainAPI.TerrainPaintTool_1.html
- [x] Remove 0 height terrain tiles
- [x] Create border meshes: https://github.com/Besjan/OSM-Interpreter/issues/5
- [x] Add border https://github.com/Besjan/OSM-Interpreter/issues/2

**Comment by Besjan** [comment]
Using Archimatix
