### ISSUE TITLE
Convert DGM XYZ data to Unity Terrain

### ISSUE THREAD

**Issue by Besjan** [Besjan/Terrain-Generator#5]
- [x] Create Terrain Data #7
- [x] Create terrain tiles from terrain data #9
- [x] Split XYZ data to 4096 resolution #6
